Moves off Travis and onto GitHub actions
This is the first hybrid Maven+Docker project to migrate off Travis to
GitHub Actions.

diff --git a/build-bin/maven/maven_build_or_unjar b/build-bin/maven/maven_build_or_unjar
--- a/build-bin/maven/maven_build_or_unjar
+++ b/build-bin/maven/maven_build_or_unjar
@@ -13,31 +13,53 @@
 # the License.
 #
 
-# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
-set -u +e
+set -ue
 
 # Like `maven_unjar`, except when the version ends in SNAPSHOT and the artifact isn't in the $PWD,
-# it is built on-demand using `mvn package`.
+# it is built on-demand using `mvn package`. MAVEN_PROJECT_BASEDIR is used when the version arg or
+# artifact is missing.
 #
 # Note: Be careful building on-demand within Docker, as it can cause high bandwidth usage, pulling
 # dependencies for the project without the benefit of caching
 
-# Use b3:0 to ensure health checks aren't traced
-$(dirname "$0")/maven_unjar $@
-UNJAR_RC=$?
+group_id=${1?group_id is required}
+artifact_id=${2?artifact_id is required}
+classifier=${3:-}
+version=${4:-}
 
-if [ "${UNJAR_RC}" == "0" ]; then exit 0; fi
+# Eagerly check if a pom is present, but don't error if it isn't
+if [ -n "${MAVEN_PROJECT_BASEDIR:-}" ] && [ -f "${MAVEN_PROJECT_BASEDIR}/pom.xml" ]; then
+  pom="${MAVEN_PROJECT_BASEDIR}/pom.xml"
+fi
+
+# Use implicit version when left out, if we can..
+if [ -z "${version}" ] && [ -n "${pom:-}" ]; then
+  version=$(sed -En 's/.*<version>(.*)<\/version>.*/\1/p' ${pom}| head -1)
+fi
+
+# rebuild the args with the version set.
+args="${group_id} ${artifact_id} ${version} ${classifier}"
+
+# Fail on unset variables, but don't quit on rc!=0, so we can log what happened
+set -u +e
+
+$(dirname "$0")/maven_unjar $args
+unjar_rc=$?
+
+if [ "${unjar_rc}" == "0" ] || [ -z "${pom:-}" ]; then
+  exit 0;
+fi
 
 case ${3?version is required} in
   *-SNAPSHOT )
     ;;
   * )
-    exit ${UNJAR_RC}
+    exit ${unjar_rc}
     ;;
 esac
 
 set -ue
 
 echo "*** Building snapshot from source..."
-mvn -T1C -q --batch-mode -DskipTests package
-exec $(dirname "$0")/maven_unjar $@
+(cd ${MAVEN_PROJECT_BASEDIR} && mvn -T1C -q --batch-mode -DskipTests package
+exec $(dirname "$0")/maven_unjar $args
