updates to latest build and zipkin (#82)

diff --git a/build-bin/maven/maven_unjar b/build-bin/maven/maven_unjar
--- a/build-bin/maven/maven_unjar
+++ b/build-bin/maven/maven_unjar
@@ -13,8 +13,6 @@
 # the License.
 #
 
-set -eu
-
 # This script gets one jar from Maven, most typically an exec or module jar, extracting its contents
 # to a directory corresponding to the artifact_id parameter.
 #
@@ -27,6 +25,8 @@ set -eu
 #
 # Ex.
 # !./module/target/zipkin-module-*-module.jar
+
+set -eu
 
 group_id=${1?group_id is required}
 artifact_id=${2?artifact_id is required}
@@ -81,7 +81,7 @@ if ! test -f ${artifact_id}.jar && [ ${is_release} = "true" ]; then
 fi
 
 if ! test -f ${artifact_id}.jar; then
-  >&2 echo "*** Failed to unjar ${qualified_jar}"
+  >&2 echo "*** Failed to build or get ${qualified_jar}"
   exit 1
 fi
 
