Moves all remaining logic that can be in build-bin from .travis.yml
4 days after raising a support issue, our Travis setup in openzipkin is
still dead. This moves all portable logic out of .travis.yml in case we
need to switch to GitHub Actions deployment.

diff --git a/build-bin/maven/maven_unjar b/build-bin/maven/maven_unjar
--- a/build-bin/maven/maven_unjar
+++ b/build-bin/maven/maven_unjar
@@ -80,7 +80,7 @@ else
 fi
 
 if ! test -f ${artifact_id}.jar; then
-  echo "*** Failed to build or get ${qualified_jar}"
+  >&2 echo "*** Failed to build or get ${qualified_jar}"
   exit 1
 fi
 
